-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 11:14:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema githubtracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema githubtracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `githubtracker` DEFAULT CHARACTER SET utf8 ;
USE `githubtracker` ;

-- -----------------------------------------------------
-- Table `githubtracker`.`githuber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `githubtracker`.`githuber` (
  `id` INT NOT NULL,
  `github_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `url` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `bio` VARCHAR(100) NULL,
  `location` VARCHAR(100) NULL,
  `avatar_url` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

CREATE USER 'djul' IDENTIFIED BY 'huacrrtc';

GRANT ALL ON `githubtracker`.* TO 'djul';
GRANT SELECT ON TABLE `githubtracker`.* TO 'djul';
GRANT SELECT, INSERT, TRIGGER ON TABLE `githubtracker`.* TO 'djul';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `githubtracker`.* TO 'djul';
GRANT EXECUTE ON ROUTINE `githubtracker`.* TO 'djul';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
